"""Public OmniVia Core memory primitives.

The package root exports the stable, public-safe primitives that consumers
usually need for memory, provenance, persistence, workspaces, ingestion, graph
links, and basic search. Subpackages remain available for more focused imports.
"""

from omnivia_memory.graph import (
    ApprovalStatus,
    Entity,
    EntityType,
    GraphSearchError,
    GraphSearchQuery,
    GraphSearchResult,
    GraphSearchResultSet,
    GraphSearchService,
    Relationship,
    RelationshipType,
)
from omnivia_memory.graph.repository import EntityRepository, RelationshipRepository
from omnivia_memory.graph.service import (
    EntityNotFoundError,
    EntityValidationError,
    GraphService,
    GraphServiceError,
    RelationshipNotFoundError,
)
from omnivia_memory.ingestion import (
    BaseChunker,
    BaseExtractor,
    CharacterChunker,
    Chunk,
    ChunkConfig,
    ChunkRepository,
    DOCXExtractor,
    ExtractionResult,
    FileInfo,
    FileScanner,
    FileType,
    IngestResult,
    IngestionPipeline,
    MarkdownExtractor,
    PDFExtractor,
    ParagraphChunker,
    ParseStatus,
    ScanOptions,
)
from omnivia_memory.app_shell_bridge import (
    AppShellBodyDescriptor,
    AppShellBridgeValidationError,
    AppShellHostContext,
    AppShellRuntimeState,
    AppShellSource,
    ValidationResult as AppShellBridgeValidationResult,
    validate_app_shell_body_descriptor,
    validate_app_shell_host_context,
)
from omnivia_memory.app_manifest import (
    AppManifest,
    AppManifestValidationError,
    AppState,
    DataSource,
    ProvenanceRequirement,
    ValidationResult as AppValidationResult,
    validate_app_manifest,
)
from omnivia_memory.component_contract import (
    ComponentContract,
    ComponentContractValidationError,
    ComponentFamily,
    ComponentInput,
    ComponentOutput,
    ComponentPermission,
    ProvenanceBehavior,
    ValidationResult as ComponentValidationResult,
    validate_component_contract,
)
from omnivia_memory.module_manifest import (
    Entrypoint,
    Integrity,
    ModuleKind,
    ModuleManifest,
    ModuleManifestValidationError,
    Permission,
    validate_module_manifest,
)
from omnivia_memory.ingestion.extractors import TextExtractor
from omnivia_memory.lifecycle import CreatedBy, LifecycleRules, LifecycleState
from omnivia_memory.memory import (
    InvalidTransitionError,
    Memory,
    MemoryCreate,
    MemoryNotFoundError,
    MemoryService,
    MemoryServiceError,
    MemoryUpdate,
)
from omnivia_memory.memory_graph import (
    EvidenceGraphResponse,
    GraphPreviewResponse,
    MemoryGraphFixture,
    RetrievalTrace,
    build_memory_graph_fixture,
)
from omnivia_memory.persistence import Database, get_database
from omnivia_memory.persistence.database import DatabaseConfig
from omnivia_memory.persistence.repositories import MemoryRepository
from omnivia_memory.provenance import Source, SourceType
from omnivia_memory.search import SearchService
from omnivia_memory.workspace import (
    ImportSummary,
    Workspace,
    WorkspaceCreate,
    WorkspaceIndexStatus,
    WorkspaceRepository,
    WorkspaceService,
    WorkspaceUpdate,
)

__version__ = "0.1.0"

__all__ = [
    "AppManifest",
    "AppManifestValidationError",
    "AppState",
    "AppShellBodyDescriptor",
    "AppShellBridgeValidationError",
    "AppShellBridgeValidationResult",
    "AppShellHostContext",
    "AppShellRuntimeState",
    "AppShellSource",
    "AppValidationResult",
    "ApprovalStatus",
    "BaseChunker",
    "BaseExtractor",
    "CharacterChunker",
    "Chunk",
    "ChunkConfig",
    "ChunkRepository",
    "ComponentContract",
    "ComponentContractValidationError",
    "ComponentFamily",
    "ComponentInput",
    "ComponentOutput",
    "ComponentPermission",
    "ComponentValidationResult",
    "CreatedBy",
    "DataSource",
    "DOCXExtractor",
    "Database",
    "DatabaseConfig",
    "Entity",
    "EntityNotFoundError",
    "EntityRepository",
    "EntityType",
    "EntityValidationError",
    "Entrypoint",
    "ExtractionResult",
    "EvidenceGraphResponse",
    "FileInfo",
    "FileScanner",
    "FileType",
    "GraphService",
    "GraphServiceError",
    "GraphSearchError",
    "GraphSearchQuery",
    "GraphSearchResult",
    "GraphSearchResultSet",
    "GraphSearchService",
    "GraphPreviewResponse",
    "ImportSummary",
    "IngestResult",
    "IngestionPipeline",
    "Integrity",
    "InvalidTransitionError",
    "LifecycleRules",
    "LifecycleState",
    "MarkdownExtractor",
    "Memory",
    "MemoryCreate",
    "MemoryGraphFixture",
    "MemoryNotFoundError",
    "MemoryRepository",
    "MemoryService",
    "MemoryServiceError",
    "MemoryUpdate",
    "ModuleKind",
    "ModuleManifest",
    "ModuleManifestValidationError",
    "PDFExtractor",
    "ParagraphChunker",
    "ParseStatus",
    "Permission",
    "ProvenanceBehavior",
    "ProvenanceRequirement",
    "Relationship",
    "RelationshipNotFoundError",
    "RelationshipRepository",
    "RelationshipType",
    "RetrievalTrace",
    "ScanOptions",
    "SearchService",
    "Source",
    "SourceType",
    "TextExtractor",
    "validate_app_manifest",
    "validate_app_shell_body_descriptor",
    "validate_app_shell_host_context",
    "validate_component_contract",
    "validate_module_manifest",
    "Workspace",
    "WorkspaceCreate",
    "WorkspaceIndexStatus",
    "WorkspaceRepository",
    "WorkspaceService",
    "WorkspaceUpdate",
    "__version__",
    "build_memory_graph_fixture",
    "get_database",
]
